ServerName oscp-prep-lab

<Directory "/var/www/localhost/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

AddType application/x-httpd-php .php .phtml
DirectoryIndex index.php index.html
